services:
  qdrant:
    image: qdrant/qdrant:v1.14.1
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage

  api:
    build: .
    image: sinjy1203/llm-techpost-chatbot-api
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    command: sh -c "uv run uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped